# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MrRogers < Formula
  desc "Get a friendly quote from Mr. Rogers in your terminal."
  homepage "https://github.com/P1NK0/mr-rogers"
  version "1.0.6"

  on_macos do
    on_intel do
      url "https://github.com/P1NK0/mr-rogers/releases/download/v1.0.6/mr-rogers_1.0.6_darwin_amd64.tar.gz"
      sha256 "864574a5b8f9f0ee32eb5861cdd43aab6a1c67f6e9f68ff2f799a5fe90551afc"

      def install
        bin.install "mr-rogers"
      end
    end
    on_arm do
      url "https://github.com/P1NK0/mr-rogers/releases/download/v1.0.6/mr-rogers_1.0.6_darwin_arm64.tar.gz"
      sha256 "8d3c53591401812da75530c34e059bd197fc60de7c40e01c1c1abd1024d10984"

      def install
        bin.install "mr-rogers"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/P1NK0/mr-rogers/releases/download/v1.0.6/mr-rogers_1.0.6_linux_amd64.tar.gz"
        sha256 "494276ffceaf51e766df87b08bb5e56f718e7e3196685511e18785d41bd5fb8a"

        def install
          bin.install "mr-rogers"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/P1NK0/mr-rogers/releases/download/v1.0.6/mr-rogers_1.0.6_linux_arm64.tar.gz"
        sha256 "f787c24a171d16318e0008435f1327204f0bed80b550119df25a456115c7338e"

        def install
          bin.install "mr-rogers"
        end
      end
    end
  end
end
